server.R

replaced deprecated "size" arguement with "linewidth" for element_rect

minor change to PD binomial graph

---

R/probDist.R

Input validation is incomplete. Needs watchers to verify non-empty numericInputs and also a check to ensure x1 <= x2.
Also needs suitable default values.

Added UI for Negative Binomials

---

R/probDist.R

Italicized 'rth', and added default values

formatting tweaks

---

R/probDist.R

actual input validation still to come

update defaults, add validator placeholders

---

R/regCorr.R

additions to MLR validation

---

R/statInfr.R

File input validation completed. Added sig lvl, and multi/stacked cols inputs upon successful file upload. Validation for multi/stacked not yet complete

Almost completed KW side panel.

---

R/statInfr.R

Currently functioning using bone density stacked test data. Will work on issues with calculating wide-format data

Almost complete KW Main panel, issues w/ wide format data

---

R/statInfr.R

fixed issue with wide format data

completed KW main panel

---

R/statInfr.R

Now displays alpha as a decimal.

Minor fix to KW siglvl

---

R/statInfr.R

Changed statistic value to be rounded to 4 decimal places, and p-value to be rounded to 4 significant digits

Minor fix to rounding in KW

---

R/statInfr.R

Changed p-value rounding and added some text

Minor formatting in KW Main Panel

---

R/statInfr.R

Changed less than/greater than symbols in main panel conclusion

Minor formatting change to KW

---

R/statInfr.R

Added Analysis and Uploaded Data tabs to KW

Added tabset panel to KW

---

R/descStats.R
R/statInfr.R

SI: changed x to chi symbol in KW
DS: display SD in scientific notation if it is sufficiently small enough

Minor fixes to SI: KW and DS

---

R/statInfr.R

Changed formatting of KW tab panel headers to be consistent w/ ANOVA

SI: Minor formatting fix

---

R/statInfr.R

Changed to dynamically create uploaded data tab depending on user input. Actual uploaded data not visible yet

SI: One Pop Mean dynamic tabset

---

R/statInfr.R

This reverts commit a0de2f295a6caac0d07dca21a3dc9e7171a1079a.

Revert "SI: One Pop Mean dynamic tabset"

---

R/statInfr.R

also minor fix to 2 samp -> ind pop tabset due to duplicate tabs when selecting dep pop afterwards

SI: 2 samp -> dep pop tabset

---

R/descStats.R
R/statInfr.R

Uploaded Data tabs are now hidden if the user inputs data via other methods

SI: hide upload tabs, DS: hide upload tabs

---

R/statInfr.R

Fixed 2 samples -> 2 dependent populations Uploaded Data tab not properly hiding/showing

SI: Fix #94, minor fix to show/hide tabs

---

R/probDist.R
R/statInfr.R

SI: Yates values were not being used in final calculation - fixed. Found and fixed additional bug in which some incorrect values were being stored for Yates, resulting in slightly off calculations.

PD: Fixed prob dist table displaying with Poisson, SI: fixed incorrect yates value

---

R/statInfr.R

Changed erroneous "fix" that used na.omit(), causing over-trimming.

SI: References #110

---

R/statInfr.R

Renamed ANOVA table row labels

SI: Minor visual change

---

R/statInfr.R

Changing all instances of 'Before' and 'After' to 'Sample 1' and 'Sample 2,' respectively

SI: References #117

---

R/statInfr.R

Changed table columns when Yates' correction applied. Changed P-Value to use Yates'-corrected test statistic

SI: Task # 2 (Yates' Correction)

---

R/multipleLinearRegression.R
R/regressionAndCorrelation.R

Fixed issue #109, changed the input box, fixed subscripts, added error checking for file, ID generation for clicking on MLR.

New MLR Format 

---

R/statInfr.R

- Two Population Standard Deviation label switched back to Two Population Variances
- HT for Two Population Variances fully restored and working
- All refactoring (Std Dev -> Variances) added back

manually restored statInfr.R

---

R/statInfr.R

- removed absolute value in p-value method
- added a period to the end on the conclusion

task #101: two pop var HT minor fixes
